spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/activiti6practice?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  activiti:
#    是否查找流程文件自动部署
    check-process-definitions: false
    database-schema-update: update
